"""first migration

Revision ID: 763f86d6153d
Revises: 
Create Date: 2020-10-07 18:08:57.863264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763f86d6153d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gang',
    sa.Column('color', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('color')
    )
    op.create_index(op.f('ix_gang_color'), 'gang', ['color'], unique=False)
    op.create_table('language',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_language_code'), 'language', ['code'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('visited', sa.DateTime(), nullable=True),
    sa.Column('registered', sa.DateTime(), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=True),
    sa.Column('is_permission', sa.Boolean(), nullable=True),
    sa.Column('is_developer', sa.Boolean(), nullable=True),
    sa.Column('is_tester', sa.Boolean(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['language'], ['language.code'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('hero',
    sa.Column('user', sa.BigInteger(), nullable=False),
    sa.Column('nick', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user')
    )
    op.create_index(op.f('ix_hero_nick'), 'hero', ['nick'], unique=True)
    op.create_index(op.f('ix_hero_user'), 'hero', ['user'], unique=False)
    op.create_table('referral',
    sa.Column('invited', sa.BigInteger(), nullable=True),
    sa.Column('inviter', sa.BigInteger(), nullable=True),
    sa.Column('is_play', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['invited'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referral')
    op.drop_index(op.f('ix_hero_user'), table_name='hero')
    op.drop_index(op.f('ix_hero_nick'), table_name='hero')
    op.drop_table('hero')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_language_code'), table_name='language')
    op.drop_table('language')
    op.drop_index(op.f('ix_gang_color'), table_name='gang')
    op.drop_table('gang')
    # ### end Alembic commands ###
